site_name: UCITE Matriz
site_url: https://ucite-h12o.github.io/matriz/

nav:
  - Home: index.md
  - Ayuda uso plataforma: getting-started.md
  - Partes de la matriz:
      - Matriz fuerzas seguridad: matriz_seguridad
      - Matriz pruebas radiológicas en BAI: pruebas_radiologicas_bai
      - Matriz analíticas y POCT: analiticas
      - Matriz profilaxis antibiótica y limpieza heridas: profilaxis_atb_limpieza
      - Matriz protección personal: proteccion_personal

theme:
  name: material
  features:
    - search.suggest
    - search.highlight

plugins:
  - search:
      lang: 
        - es
        - en
      separator: '[\s\-\.]+'


extra_javascript:
  - javascripts/remove-diacritics.js