site_name: UCITE Matriz
site_url: https://ucite-h12o.github.io/matriz/

nav:
  - Home: index.md
  - Ayuda uso plataforma: getting-started.md
  - Partes de la matriz:
      - Matriz 7 - Profilaxis antibiótica y limpieza heridas: profilaxis_atb_limpieza
      - Matriz 18 - Pruebas Radiológicas en BAI: pruebas_radiologicas_bai
      - Matriz 19 - Analíticas y POCT: analiticas
      - Matriz 26 - Fuerzas Seguridad: matriz_seguridad  
      - Matriz 31 - Protección personal: proteccion_personal

theme:
  name: material
  features:
    - search.suggest
    - search.highlight

plugins:
  - search:
      lang: 
        - es
        - en
      separator: '[\s\-\.]+'


extra_javascript:
  - javascripts/remove-diacritics.js