site_name: UCITE Matriz
site_url: https://ucite-h12o.github.io/matriz/

nav:
  - Home: index.md
  - Ayuda uso plataforma: getting-started.md
  - 1 - Preaviso: preaviso
  - 7 - Profilaxis antibiótica y limpieza heridas: profilaxis_atb_limpieza
  - 9 - Canalización de vías venosas y arteriales: canalizacion_vias
  - 14 - Resucitación hemostática: resucitacion_hemostatica
  - 15 - Traslado intrahospitalario del paciente: traslado_intrahosp
  - 18 - Pruebas Radiológicas en BAI: pruebas_radiologicas_bai
  - 19 - Analíticas y POCT: analiticas
  - 25 - Manejo de objetos personales (pertenencias): pertenencias
  - 26 - Fuerzas Seguridad: matriz_seguridad  
  - 28 - Sedación consciente: sedacion_consciente
  - 31 - Protección personal: proteccion_personal
  - VÍDEOS: videos

theme:
  name: material
  features:
    - search.suggest
    - search.highlight

plugins:
  - search:
      prebuild_index: false
      lang: 
        - es
        - en
      separator: '[\s\-\.]+'
  - mkdocs-video:
      is_video: True
      video_autoplay: false


extra_javascript:
  - javascripts/remove-diacritics.js
  - https://hypothes.is/embed.js